// This file is automatically generated from your CSS. Any edits will be overwritten.
export const barChartRects: string;
export const barChartAxis: string;
export const graph: string;
export const xLabel: string;
export const divisions: string;
